import type { Metadata } from "next";
import "./globals.css";
import { Providers } from './providers';
import { fonts } from './fonts';
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Starwars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.variables}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
